### ISSUE TITLE
Python 3.8 `ioos_qc` leads to an ImportError with xarray, but Python 3.7 does not.

### ISSUE THREAD

**Issue by kthyng** [ioos/ioos_qc#77]
```
mamba create --name test-xarray-ioosqc38 python=3.8 xarray ioos_qc
conda activate test-xarray-ioosqc38
```
and then in a python window trying:
```
from ioos_qc.streams import NumpyStream
```
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kthyng/miniconda3/envs/test-xarray-ioosqc/lib/python3.8/site-packages/ioos_qc/streams.py", line 10, in <module>
    from xarray.core.indexing import remap_label_indexers
ImportError: cannot import name 'remap_label_indexers' from 'xarray.core.indexing' (/Users/kthyng/miniconda3/envs/test-xarray-ioosqc/lib/python3.8/site-packages/xarray/core/indexing.py)
```

However, the following environment with Python 3.7 does not lead to an error:
```
mamba create --name test-xarray-ioosqc37 python=3.7 xarray ioos_qc
```

**Comment by ocefpaf** [comment]
This is most likely a packaging problem. Can you do a `conda list` on both environments and post for us here?

**Comment by kthyng** [comment]
Thanks for figuring that out!
